declaration="declaration"
application="application"
configuration="configuration"
spring="spring"
semaphore="semaphore"
initialization="initialization"
delegation="delegation"
polymorphism="polymorphism"
communication="communication"
distributed="distributed"
immutability="immutability"
semantics="semantics"
specification="specification"
architecture="architecture"
concurrency="concurrency"
hierarchical="hierarchical"
implicit="implicit"
introspection="introspection"
assembly="assembly"
associative="associative"
efficiency="efficiency"
encapsulation="encapsulation"
expression="expression"
algorithm="algorithm"
invariants="invariants"
parallel="parallel"
aggregation="aggregation"
authorization="authorization"
warehouse="warehouse"
incremental="incremental"
administrator="administrator"
infrastructure="infrastructure"
candidates="candidates"
milestone="milestone"
release="release"
documentation="documentation"
framework="framework"
synchronization="synchronization"
performance="performance"
gracefully="gracefully"
mutexes="mutexes"